
your message was successfully posted to Webex Teams

Microarray

 was successfully posted to Webex Teams on 2022-11-10 12:00:03.000062

x86

 was successfully posted to Webex Teams on 2022-11-11 12:00:03.636146

Product-family engineering (PFE)

 was successfully posted to Webex Teams on 2022-11-12 12:00:01.336144

traceroute

 was successfully posted to Webex Teams on 2022-11-13 12:00:02.048390

Wantrepreneur

 was successfully posted to Webex Teams on 2022-11-14 12:00:04.103672

Kubernetes (K8s)

 was successfully posted to Webex Teams on 2022-11-15 12:00:02.506413

Buffer overflow

 was successfully posted to Webex Teams on 2022-11-16 12:00:04.341348

Sanitization

 was successfully posted to Webex Teams on 2022-11-17 12:00:02.835602

XML

 was successfully posted to Webex Teams on 2022-11-18 12:00:02.367360

Cloud native

 was successfully posted to Webex Teams on 2022-11-19 12:00:03.541210

Blacksurfing

 was successfully posted to Webex Teams on 2022-11-20 12:00:02.842396

Separation of concerns

 was successfully posted to Webex Teams on 2022-11-21 12:00:03.429271

Out-of-band data

 was successfully posted to Webex Teams on 2022-11-22 12:00:03.868055

Managed object (MO)

 was successfully posted to Webex Teams on 2022-11-23 12:00:01.993719

Regression testing

 was successfully posted to Webex Teams on 2022-11-24 12:00:02.475856

Source routing

 was successfully posted to Webex Teams on 2022-11-25 12:00:03.735158

OpenFlow

 was successfully posted to Webex Teams on 2022-11-26 12:00:03.301218

Coupled

 was successfully posted to Webex Teams on 2022-11-27 12:00:04.032659

Driver

 was successfully posted to Webex Teams on 2022-11-28 12:00:04.141343

Marshalling

 was successfully posted to Webex Teams on 2022-11-29 12:00:02.286923

HTTP return codes

 was successfully posted to Webex Teams on 2022-11-30 12:00:04.297762

Scalability

 was successfully posted to Webex Teams on 2022-12-01 12:00:03.274682

Cliff effect

 was successfully posted to Webex Teams on 2022-12-02 12:00:02.800646

Expireware

 was successfully posted to Webex Teams on 2022-12-03 12:00:02.848086

Shotgun debugging

 was successfully posted to Webex Teams on 2022-12-04 12:00:02.204787

Dynamic application security testing (DAST)

 was successfully posted to Webex Teams on 2022-12-05 12:00:03.462608

Distributed Overlay Virtual Ethernet (DOVE)

 was successfully posted to Webex Teams on 2022-12-06 12:00:04.627753

Full-stack observability

 was successfully posted to Webex Teams on 2022-12-07 12:00:01.656258

Ergonomics

 was successfully posted to Webex Teams on 2022-12-08 12:00:01.809690

Ergonomics

 was successfully posted to LinkedIn

FIFO

 was successfully posted to Webex Teams on 2022-12-09 12:00:02.220289

FIFO

 was successfully posted to LinkedIn

Rewrite

 was successfully posted to Webex Teams on 2022-12-10 12:00:02.314256

Rewrite

 was successfully posted to LinkedIn

Cobrowsing

 was successfully posted to Webex Teams on 2022-12-11 12:00:01.355919

Cobrowsing

 was successfully posted to LinkedIn

Shim

 was successfully posted to Webex Teams on 2022-12-12 12:00:03.537346

Shim

 was successfully posted to LinkedIn

Compound document

 was successfully posted to Webex Teams on 2022-12-13 12:00:02.344415

Compound document

 was successfully posted to LinkedIn

Syntactic sugar

 was successfully posted to Webex Teams on 2022-12-14 12:00:03.455760

Syntactic sugar

 was successfully posted to LinkedIn

Cartesian coordinate system

 was successfully posted to Webex Teams on 2022-12-15 12:00:03.280170

Cartesian coordinate system

 was successfully posted to LinkedIn

CSS (Cascading Style Sheets)

 was successfully posted to Webex Teams on 2022-12-16 12:00:02.448468

CSS (Cascading Style Sheets)

 was successfully posted to LinkedIn

initRD

 was successfully posted to Webex Teams on 2022-12-17 12:00:03.070771

initRD

 was successfully posted to LinkedIn

Magic

 was successfully posted to Webex Teams on 2022-12-18 12:00:02.975988

Magic

 was successfully posted to LinkedIn

Forward chaining

 was successfully posted to Webex Teams on 2022-12-19 12:00:02.563396

Forward chaining

 was successfully posted to LinkedIn

Microservice

 was successfully posted to Webex Teams on 2022-12-20 12:00:02.680349

Microservice

 was successfully posted to LinkedIn

Alphanumerish

 was successfully posted to Webex Teams on 2022-12-21 12:00:02.826520

Alphanumerish

 was successfully posted to LinkedIn

Dogfooding

 was successfully posted to Webex Teams on 2022-12-22 12:00:02.125963

Dogfooding

 was successfully posted to LinkedIn

Bridgeware

 was successfully posted to Webex Teams on 2022-12-23 12:00:02.159709

Bridgeware

 was successfully posted to LinkedIn
failed with statusCode: 400
please check the identifier of the room you're attempting to post to...

John McCarthy

 was successfully posted to LinkedIn

Network management software

 was successfully posted to Webex Teams on 2022-12-25 12:00:04.139245

Network management software

 was successfully posted to LinkedIn

Management information base (MIB

 was successfully posted to Webex Teams on 2022-12-26 12:00:02.849550

Management information base (MIB

 was successfully posted to LinkedIn

Database engine

 was successfully posted to Webex Teams on 2022-12-27 12:00:05.302042

Database engine

 was successfully posted to LinkedIn

Gender changer

 was successfully posted to Webex Teams on 2022-12-28 12:00:01.364355

Gender changer

 was successfully posted to LinkedIn

Application service provider (ASP)

 was successfully posted to Webex Teams on 2022-12-29 12:00:02.216919

Application service provider (ASP)

 was successfully posted to LinkedIn

Stack

 was successfully posted to Webex Teams on 2022-12-30 12:00:01.928853

Stack

 was successfully posted to LinkedIn

Composite pattern

 was successfully posted to Webex Teams on 2022-12-31 12:00:02.405087

Composite pattern

 was successfully posted to LinkedIn

Hypermedia

 was successfully posted to Webex Teams on 2023-01-01 12:00:02.494022

Hypermedia

 was successfully posted to LinkedIn

Biomimetics

 was successfully posted to Webex Teams on 2023-01-02 12:00:03.042389

Biomimetics

 was successfully posted to LinkedIn

gNMI

 was successfully posted to Webex Teams on 2023-01-03 12:00:02.062039

gNMI

 was successfully posted to LinkedIn

SOAP

 was successfully posted to Webex Teams on 2023-01-04 12:00:03.297715

SOAP

 was successfully posted to LinkedIn

Weighted round robin

 was successfully posted to Webex Teams on 2023-01-05 12:00:04.816327

Weighted round robin

 was successfully posted to LinkedIn

Data migration

 was successfully posted to Webex Teams on 2023-01-06 12:00:02.787417

Data migration

 was successfully posted to LinkedIn

Data smog

 was successfully posted to Webex Teams on 2023-01-07 12:00:15.601785

Data smog

 was successfully posted to LinkedIn

Transceiver

 was successfully posted to Webex Teams on 2023-01-08 12:00:02.882194

Transceiver

 was successfully posted to LinkedIn

Captology

 was successfully posted to Webex Teams on 2023-01-09 12:00:02.595842

Captology

 was successfully posted to LinkedIn

Theory of constraints (TOC)

 was successfully posted to Webex Teams on 2023-01-10 12:00:03.029983

Theory of constraints (TOC)

 was successfully posted to LinkedIn

Greenware

 was successfully posted to Webex Teams on 2023-01-11 12:00:02.535579

Greenware

 was successfully posted to LinkedIn

Coding best practices

 was successfully posted to Webex Teams on 2023-01-12 12:00:02.591521

Coding best practices

 was successfully posted to LinkedIn

Blockchain

 was successfully posted to Webex Teams on 2023-01-13 12:00:03.130475

Blockchain

 was successfully posted to LinkedIn

Expert system

 was successfully posted to Webex Teams on 2023-01-14 12:00:03.329545

Expert system

 was successfully posted to LinkedIn

Bug compatibility

 was successfully posted to Webex Teams on 2023-01-15 12:00:03.046133

Bug compatibility

 was successfully posted to LinkedIn

Standard operating environment (SOE)

 was successfully posted to Webex Teams on 2023-01-16 12:00:02.038494

Standard operating environment (SOE)

 was successfully posted to LinkedIn

Function as a Service (FaaS)

 was successfully posted to Webex Teams on 2023-01-17 12:00:02.082256

Function as a Service (FaaS)

 was successfully posted to LinkedIn

Source Code Management (SCM)

 was successfully posted to Webex Teams on 2023-01-18 12:00:04.467930

Source Code Management (SCM)

 was successfully posted to LinkedIn

Instrumental convergence

 was successfully posted to Webex Teams on 2023-01-19 12:00:03.316384

Instrumental convergence

 was successfully posted to LinkedIn

Web3

 was successfully posted to Webex Teams on 2023-01-20 12:00:03.926413

Web3

 was successfully posted to LinkedIn

Kanban

 was successfully posted to Webex Teams on 2023-01-21 12:00:01.728702

Kanban

 was successfully posted to LinkedIn

Exploratory model

 was successfully posted to Webex Teams on 2023-01-22 12:00:01.802902

Exploratory model

 was successfully posted to LinkedIn

Dark web

 was successfully posted to Webex Teams on 2023-01-23 12:00:02.828702

Dark web

 was successfully posted to LinkedIn

Code ninja

 was successfully posted to Webex Teams on 2023-01-24 12:00:02.783372

Code ninja

 was successfully posted to LinkedIn

Dereference

 was successfully posted to Webex Teams on 2023-01-25 12:00:02.638255

Dereference

 was successfully posted to LinkedIn

Vampire device

 was successfully posted to Webex Teams on 2023-01-26 12:00:02.677186

Vampire device

 was successfully posted to LinkedIn

Poisson distribution

 was successfully posted to Webex Teams on 2023-01-27 12:00:04.141359

Poisson distribution

 was successfully posted to LinkedIn

Primitive data type

 was successfully posted to Webex Teams on 2023-01-28 12:00:06.338090

Primitive data type

 was successfully posted to LinkedIn

Internet of behaviors (IoB)

 was successfully posted to Webex Teams on 2023-01-29 12:00:02.704202

Internet of behaviors (IoB)

 was successfully posted to LinkedIn

Always On VPN (AOVPN)

 was successfully posted to Webex Teams on 2023-01-30 12:00:01.888137

Always On VPN (AOVPN)

 was successfully posted to LinkedIn

Virtual appliance

 was successfully posted to Webex Teams on 2023-01-31 12:00:01.890466

Virtual appliance

 was successfully posted to LinkedIn

Big data

 was successfully posted to Webex Teams on 2023-02-01 12:00:03.217894

Big data

 was successfully posted to LinkedIn

First-class function

 was successfully posted to Webex Teams on 2023-02-02 12:00:03.569392

First-class function

 was successfully posted to LinkedIn

Modeling language

 was successfully posted to Webex Teams on 2023-02-03 12:00:04.131009

Modeling language

 was successfully posted to LinkedIn

Splinternet

 was successfully posted to Webex Teams on 2023-02-04 12:00:03.720891

Splinternet

 was successfully posted to LinkedIn

Multiexperience (MX)

 was successfully posted to Webex Teams on 2023-02-05 12:00:02.147263
failed with statusCode: 401

Factory

 was successfully posted to Webex Teams on 2023-02-06 12:00:02.234780

Factory

 was successfully posted to LinkedIn

QUIC

 was successfully posted to Webex Teams on 2023-02-07 12:00:02.318446

QUIC

 was successfully posted to LinkedIn

Integrated development environment (IDE)

 was successfully posted to Webex Teams on 2023-02-08 12:00:04.269161

Integrated development environment (IDE)

 was successfully posted to LinkedIn

Eastbound/Westbound interfaces

 was successfully posted to Webex Teams on 2023-02-09 12:00:03.746791

Eastbound/Westbound interfaces

 was successfully posted to LinkedIn

Cramming (fraud)

 was successfully posted to Webex Teams on 2023-02-10 12:00:03.289761

Cramming (fraud)

 was successfully posted to LinkedIn

alt tag

 was successfully posted to Webex Teams on 2023-02-11 12:00:02.195824

alt tag

 was successfully posted to LinkedIn

Places with ‘Silicon’ names

 was successfully posted to Webex Teams on 2023-02-12 12:00:01.994232

Places with ‘Silicon’ names

 was successfully posted to LinkedIn

White hat vs. Black hat vs. Grey Hat

 was successfully posted to Webex Teams on 2023-02-13 12:00:03.952979

White hat vs. Black hat vs. Grey Hat

 was successfully posted to LinkedIn

Backhaul

 was successfully posted to Webex Teams on 2023-02-14 12:00:02.474632

Backhaul

 was successfully posted to LinkedIn

Elegant solution

 was successfully posted to Webex Teams on 2023-02-15 12:00:06.440224

Elegant solution

 was successfully posted to LinkedIn

Boilerplate code

 was successfully posted to Webex Teams on 2023-02-16 12:00:02.901198

Boilerplate code

 was successfully posted to LinkedIn

Sanity testing

 was successfully posted to Webex Teams on 2023-02-17 12:00:03.003232

Sanity testing

 was successfully posted to LinkedIn

Softlifting

 was successfully posted to Webex Teams on 2023-02-18 12:00:02.410601

Softlifting

 was successfully posted to LinkedIn

'This changes everything'

 was successfully posted to Webex Teams on 2023-02-19 12:00:04.342018

'This changes everything'

 was successfully posted to LinkedIn

AMD (Advanced Micro Devices, Inc.)

 was successfully posted to Webex Teams on 2023-02-20 12:00:03.153023

AMD (Advanced Micro Devices, Inc.)

 was successfully posted to LinkedIn

Polymorphism

 was successfully posted to Webex Teams on 2023-02-21 12:00:03.448993

Polymorphism

 was successfully posted to LinkedIn

Kludge

 was successfully posted to Webex Teams on 2023-02-22 12:00:01.965173

Kludge

 was successfully posted to LinkedIn
failed with statusCode: 400
please check the identifier of the room you're attempting to post to...

Test-driven development (TDD)

 was successfully posted to LinkedIn

Software brittleness

 was successfully posted to Webex Teams on 2023-02-24 12:00:03.011790

Software brittleness

 was successfully posted to LinkedIn
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fad2ee20e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad2ee20e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 145, in <module>
    res = send_it(TEAMS_ACCESS_TOKEN, teams_room, the_message)
  File "chatops.py", line 19, in send_it
    return requests.post("https://api.ciscospark.com/v1/messages/", headers=header, data=json.dumps(data), verify=True)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad2ee20e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Systems programmer

 was successfully posted to Webex Teams on 2023-02-26 12:00:03.021207

Systems programmer

 was successfully posted to LinkedIn

Web crawler

 was successfully posted to Webex Teams on 2023-02-27 12:00:02.654434

Web crawler

 was successfully posted to LinkedIn

Exception handling

 was successfully posted to Webex Teams on 2023-02-28 12:00:06.164990

Exception handling

 was successfully posted to LinkedIn

Information Technology Infrastructure Library (ITIL)

 was successfully posted to Webex Teams on 2023-03-01 12:00:02.778824

Information Technology Infrastructure Library (ITIL)

 was successfully posted to LinkedIn

Halting problem

 was successfully posted to Webex Teams on 2023-03-02 12:00:03.350807

Halting problem

 was successfully posted to LinkedIn

Artificial general intelligence (AGI)

 was successfully posted to Webex Teams on 2023-03-03 12:00:02.682388

Artificial general intelligence (AGI)

 was successfully posted to LinkedIn
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa8eb03be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8eb03be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 145, in <module>
    res = send_it(TEAMS_ACCESS_TOKEN, teams_room, the_message)
  File "chatops.py", line 19, in send_it
    return requests.post("https://api.ciscospark.com/v1/messages/", headers=header, data=json.dumps(data), verify=True)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8eb03be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Channel coding

 was successfully posted to Webex Teams on 2023-03-06 12:00:02.585769

Channel coding

 was successfully posted to LinkedIn

Source-to-source compiler (S2S compiler)

 was successfully posted to Webex Teams on 2023-03-07 12:00:04.864508

Source-to-source compiler (S2S compiler)

 was successfully posted to LinkedIn

Authenticated Encryption (AE) and Authenticated Encryption with Associated Data (AEAD)

 was successfully posted to Webex Teams on 2023-03-08 12:00:03.927535

Authenticated Encryption (AE) and Authenticated Encryption with Associated Data (AEAD)

 was successfully posted to LinkedIn

Query language

 was successfully posted to Webex Teams on 2023-03-09 12:00:02.774336

Query language

 was successfully posted to LinkedIn

OAM multiplexing

 was successfully posted to Webex Teams on 2023-03-14 12:00:03.422865

OAM multiplexing

 was successfully posted to LinkedIn

Blook

 was successfully posted to Webex Teams on 2023-03-15 12:00:03.707999

Blook

 was successfully posted to LinkedIn

Y2K38

 was successfully posted to Webex Teams on 2023-03-20 12:00:03.572566

Y2K38

 was successfully posted to LinkedIn

Best current practice (BCP)

 was successfully posted to Webex Teams on 2023-03-21 12:00:04.070186

Best current practice (BCP)

 was successfully posted to LinkedIn

Dynamic Multipoint Virtual Private Network (DMVPN)

 was successfully posted to Webex Teams on 2023-03-23 12:00:04.486214

Dynamic Multipoint Virtual Private Network (DMVPN)

 was successfully posted to LinkedIn

Dynamic typing vs. static typing

 was successfully posted to Webex Teams on 2023-03-28 12:00:04.387009

Dynamic typing vs. static typing

 was successfully posted to LinkedIn

Zombie API

 was successfully posted to Webex Teams on 2023-03-29 12:00:04.065228

Zombie API

 was successfully posted to LinkedIn

Cache coherency

 was successfully posted to Webex Teams on 2023-03-30 12:00:04.672233

Cache coherency

 was successfully posted to LinkedIn

Cloud bursting

 was successfully posted to Webex Teams on 2023-03-31 12:00:06.838154

Cloud bursting

 was successfully posted to LinkedIn

Machine learning

 was successfully posted to Webex Teams on 2023-04-03 12:00:03.688862

Machine learning

 was successfully posted to LinkedIn

Die

 was successfully posted to Webex Teams on 2023-04-04 12:00:03.268082

Die

 was successfully posted to LinkedIn

Five nines

 was successfully posted to Webex Teams on 2023-04-05 12:00:03.806221

Five nines

 was successfully posted to LinkedIn

Multicloud

 was successfully posted to Webex Teams on 2023-04-06 12:00:04.892955

Multicloud

 was successfully posted to LinkedIn

AWS Lambda

 was successfully posted to Webex Teams on 2023-04-10 12:00:02.798019
failed with statusCode: 401

Monorepo

 was successfully posted to Webex Teams on 2023-04-11 12:00:03.235477

Monorepo

 was successfully posted to LinkedIn

Distributed apps

 was successfully posted to Webex Teams on 2023-04-13 12:00:03.885629

Distributed apps

 was successfully posted to LinkedIn

Spiral development

 was successfully posted to Webex Teams on 2023-04-14 12:00:02.020053

Spiral development

 was successfully posted to LinkedIn

Lindy effect

 was successfully posted to Webex Teams on 2023-04-17 12:00:02.389302

Lindy effect

 was successfully posted to LinkedIn

Bill shock

 was successfully posted to Webex Teams on 2023-04-19 12:00:03.511919

Bill shock

 was successfully posted to LinkedIn

Botnet

 was successfully posted to Webex Teams on 2023-04-20 12:00:02.537717

Botnet

 was successfully posted to LinkedIn

Buffer underrun

 was successfully posted to Webex Teams on 2023-04-21 12:00:03.001532

Buffer underrun

 was successfully posted to LinkedIn

XSD

 was successfully posted to Webex Teams on 2023-04-24 12:00:04.366275

XSD

 was successfully posted to LinkedIn

Internet of things (IoT)

 was successfully posted to Webex Teams on 2023-04-25 12:00:03.390341

Internet of things (IoT)

 was successfully posted to LinkedIn

Vaporware

 was successfully posted to Webex Teams on 2023-04-26 12:00:02.611294

Vaporware

 was successfully posted to LinkedIn

Glocalization

 was successfully posted to Webex Teams on 2023-04-27 12:00:03.082570

Glocalization

 was successfully posted to LinkedIn

Lint

 was successfully posted to Webex Teams on 2023-04-28 12:00:04.069337

Lint

 was successfully posted to LinkedIn

Human Level Machine Intelligence (HLMI)

 was successfully posted to Webex Teams on 2023-05-01 12:00:03.643915

Human Level Machine Intelligence (HLMI)

 was successfully posted to LinkedIn

Big Blue

 was successfully posted to Webex Teams on 2023-05-02 12:00:02.547742

Big Blue

 was successfully posted to LinkedIn

Acceptable use policy (AUP)

 was successfully posted to Webex Teams on 2023-05-04 12:00:03.002124

Acceptable use policy (AUP)

 was successfully posted to LinkedIn

BLUF (bottom line up front)

 was successfully posted to Webex Teams on 2023-05-05 12:00:08.597098

BLUF (bottom line up front)

 was successfully posted to LinkedIn
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd8c153de50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8c153de50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 146, in <module>
    res = send_it(TEAMS_ACCESS_TOKEN, teams_room, the_message)
  File "chatops.py", line 19, in send_it
    return requests.post("https://api.ciscospark.com/v1/messages/", headers=header, data=json.dumps(data), verify=True)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8c153de50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Idempotent

 was successfully posted to Webex Teams on 2023-05-07 12:00:02.513616

Idempotent

 was successfully posted to LinkedIn

CI/CD

 was successfully posted to Webex Teams on 2023-05-08 12:00:03.636088

CI/CD

 was successfully posted to LinkedIn

Write-only code

 was successfully posted to Webex Teams on 2023-05-09 12:00:03.300742

Write-only code

 was successfully posted to LinkedIn

Monte Carlo method

 was successfully posted to Webex Teams on 2023-05-10 12:00:06.968929

Monte Carlo method

 was successfully posted to LinkedIn

Software agent

 was successfully posted to Webex Teams on 2023-05-11 12:00:04.423217

Software agent

 was successfully posted to LinkedIn

Software Image Management (SWIM)

 was successfully posted to Webex Teams on 2023-05-12 12:00:03.015183

Software Image Management (SWIM)

 was successfully posted to LinkedIn

I/O

 was successfully posted to Webex Teams on 2023-05-15 12:00:03.120826

I/O

 was successfully posted to LinkedIn

Immutable infrastructure

 was successfully posted to Webex Teams on 2023-05-16 12:00:03.612447

Immutable infrastructure

 was successfully posted to LinkedIn

Endianness

 was successfully posted to Webex Teams on 2023-05-17 12:00:03.329589

Endianness

 was successfully posted to LinkedIn

DevSecOps

 was successfully posted to Webex Teams on 2023-05-23 12:00:04.140579

DevSecOps

 was successfully posted to LinkedIn

Version control

 was successfully posted to Webex Teams on 2023-05-24 12:00:04.866509

Version control

 was successfully posted to LinkedIn

Inter-process communication (IPC)

 was successfully posted to Webex Teams on 2023-05-25 12:00:03.488503

Inter-process communication (IPC)

 was successfully posted to LinkedIn

Pasta theory of programming

 was successfully posted to Webex Teams on 2023-05-26 12:00:02.671223

Pasta theory of programming

 was successfully posted to LinkedIn

Legacy system

 was successfully posted to Webex Teams on 2023-05-30 12:00:05.271082

Legacy system

 was successfully posted to LinkedIn

The Woz

 was successfully posted to Webex Teams on 2023-05-31 12:00:06.816543

The Woz

 was successfully posted to LinkedIn

Software development kit (SDK)

 was successfully posted to Webex Teams on 2023-06-02 12:00:02.933612

Software development kit (SDK)

 was successfully posted to LinkedIn

Smoke testing

 was successfully posted to Webex Teams on 2023-06-05 12:00:04.245777
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 162, in <module>
    res2 = post(profile_id, li_access_token, random_word_name, definition, word_url)
  File "chatops.py", line 55, in post
    response = requests.post(url, headers=headers, json=post_data)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

Software-defined everything (SDE/SDx)

 was successfully posted to Webex Teams on 2023-06-13 12:00:06.941109
failed with statusCode: 401

Capability Maturity Model

 was successfully posted to Webex Teams on 2023-06-14 12:00:05.577646
failed with statusCode: 401

Robotic process automation

 was successfully posted to Webex Teams on 2023-06-15 12:00:06.577757
failed with statusCode: 401
failed with statusCode: 400
please check the identifier of the room you're attempting to post to...
failed with statusCode: 401

Branching

 was successfully posted to Webex Teams on 2023-06-17 12:00:03.170591
failed with statusCode: 401

Alice (software)

 was successfully posted to Webex Teams on 2023-06-18 12:00:02.674993
failed with statusCode: 401

Captive portal

 was successfully posted to Webex Teams on 2023-06-19 12:00:03.149604
failed with statusCode: 401

Deployment vs. Provisioning

 was successfully posted to Webex Teams on 2023-06-20 12:00:06.423559
failed with statusCode: 401

Decentralized application

 was successfully posted to Webex Teams on 2023-06-22 12:00:09.526405
failed with statusCode: 401

Backscatter spam

 was successfully posted to Webex Teams on 2023-06-23 12:00:03.078942
failed with statusCode: 401

Rasterisation

 was successfully posted to Webex Teams on 2023-06-26 12:00:07.097437
failed with statusCode: 401

Liveware

 was successfully posted to Webex Teams on 2023-06-27 12:00:07.402202
failed with statusCode: 401

Brogrammer

 was successfully posted to Webex Teams on 2023-06-28 12:00:03.859682
failed with statusCode: 401

Link aggregation

 was successfully posted to Webex Teams on 2023-06-29 12:00:07.743436
failed with statusCode: 401

Segment routing

 was successfully posted to Webex Teams on 2023-07-06 12:00:02.149891

Segment routing

 was successfully posted to LinkedIn

Bootstrapping

 was successfully posted to Webex Teams on 2023-07-07 12:00:02.956453

Bootstrapping

 was successfully posted to LinkedIn

Remote procedure call (RPC)

 was successfully posted to Webex Teams on 2023-07-10 12:00:08.458358

Remote procedure call (RPC)

 was successfully posted to LinkedIn

Anti-pattern

 was successfully posted to Webex Teams on 2023-07-11 12:00:08.214592

Anti-pattern

 was successfully posted to LinkedIn

Block Cipher vs Stream Cipher

 was successfully posted to Webex Teams on 2023-07-12 12:00:07.202593

Block Cipher vs Stream Cipher

 was successfully posted to LinkedIn

Neural networks

 was successfully posted to Webex Teams on 2023-07-13 12:00:07.894566

Neural networks

 was successfully posted to LinkedIn

NaaS

 was successfully posted to Webex Teams on 2023-07-14 12:00:04.045097

NaaS

 was successfully posted to LinkedIn

alias

 was successfully posted to Webex Teams on 2023-07-17 12:00:04.217288

alias

 was successfully posted to LinkedIn

Network programmability

 was successfully posted to Webex Teams on 2023-07-18 12:00:04.614607

Network programmability

 was successfully posted to LinkedIn

Interface to the Routing System (i2rs)

 was successfully posted to Webex Teams on 2023-07-19 12:00:03.890968

Interface to the Routing System (i2rs)

 was successfully posted to LinkedIn
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8c0f222e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c0f222e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 146, in <module>
    res = send_it(TEAMS_ACCESS_TOKEN, teams_room, the_message)
  File "chatops.py", line 19, in send_it
    return requests.post("https://api.ciscospark.com/v1/messages/", headers=header, data=json.dumps(data), verify=True)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c0f222e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Fibre Channel

 was successfully posted to Webex Teams on 2023-07-21 12:00:03.190083

Fibre Channel

 was successfully posted to LinkedIn

Platform engineering

 was successfully posted to Webex Teams on 2023-07-22 12:00:02.854974

Platform engineering

 was successfully posted to LinkedIn
failed with statusCode: 400
please check the identifier of the room you're attempting to post to...

Programming kata

 was successfully posted to LinkedIn

Uniform Resource Identifier (URI)

 was successfully posted to Webex Teams on 2023-07-24 12:00:04.157399

Uniform Resource Identifier (URI)

 was successfully posted to LinkedIn

Dvorak vs. QWERTY

 was successfully posted to Webex Teams on 2023-07-25 12:00:04.394761

Dvorak vs. QWERTY

 was successfully posted to LinkedIn

Aspect-Oriented Programming (AOP)

 was successfully posted to Webex Teams on 2023-07-26 12:00:03.532927

Aspect-Oriented Programming (AOP)

 was successfully posted to LinkedIn

Loose coupling

 was successfully posted to Webex Teams on 2023-07-27 12:00:06.662366
failed with statusCode: 500
Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc61b87be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc61b87be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatops.py", line 146, in <module>
    res = send_it(TEAMS_ACCESS_TOKEN, teams_room, the_message)
  File "chatops.py", line 19, in send_it
    return requests.post("https://api.ciscospark.com/v1/messages/", headers=header, data=json.dumps(data), verify=True)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/alexstev/Documents/CiscoDevNet/code/wod/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ciscospark.com', port=443): Max retries exceeded with url: /v1/messages/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc61b87be50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Crippleware

 was successfully posted to Webex Teams on 2023-07-31 12:00:04.730980

Crippleware

 was successfully posted to LinkedIn

YAML

 was successfully posted to Webex Teams on 2023-08-01 12:00:03.614859

YAML

 was successfully posted to LinkedIn
